# Version: 0.2.0
generate_web_io:
  name: Web-IO Export
  description: Generates a JSON for Comexio import or uploads it directly.
  fields:
    upload:
      name: Direct upload
      description: If enabled, the device class is sent directly to Comexio.
      selector:
        boolean:
