name: CI

on:
  push:
    paths:
      - 'custom_components/**'
      - 'pyproject.toml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'custom_components/**'
      - 'pyproject.toml'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  ruff:
    name: Ruff Linter & Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff Check
        run: ruff check .
      - name: Run Ruff Format
        run: ruff format --check .

  security:
    name: Security check - Bandit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'
      - name: Install Bandit
        run: pip install bandit
      - name: Security check - Bandit
        run: bandit -r custom_components/comexio

  validate:
    name: Check hassfest
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
