name: OSV-Scanner

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  schedule:
    - cron: '30 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan-pr:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@6e4298ebc4db23e847df9b2e2de2939d6f066c67" # v2.5.1

  scan-scheduled:
    if: ${{ contains(fromJSON('["push", "schedule", "workflow_dispatch"]'), github.event_name) }}
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@6e4298ebc4db23e847df9b2e2de2939d6f066c67" # v2.5.1
